### ISSUE TITLE
Signing fails silently if JWK is not reachable?

### ISSUE THREAD

**Issue by mattkendall** [devopsfaith/krakend-jose#29]
In my local testing using the `1.1.1` and `1` versions of the krakend docker container, the JOSE plugin appears to access the `jwks-url` once on startup. If it fails to download the JWK key object, then Kraken continues to serve content, but signing is skipped.

Given a simple signer configuration for a dummy `/authn` endpoint, based on the docs:

```
{
   "github.com/devopsfaith/krakend-jose/signer":{
      "alg":"HS256",
      "kid":"jwk",
      "keys-to-sign":[
         "access_token",
         "refresh_token"
      ],
      "jwk-url":"http://authmock:8080/jwk/symmetric.json",
      "disable_jwk_security":true
   }
}
```

If the `authmock` service is offline when I start Kraken, then I see these log messages:

```
[KRAKEND] 2020/03/25 - 14:37:20.803 ▶ ERROR Get "http://authmock:8080/jwk/symmetric.json": dial tcp 23.217.138.110:8080: connect: connection refused /authn
...
[KRAKEND] 2020/03/25 - 14:37:20.803 ▶ INFO JOSE: validator disabled for the endpoint /authn
```

Posting to `/authn` (based on the example from the docs), returns the content without signing the keys:

```
# curl -s -X POST --data '{ "user": "alice" }' http://kraken.local/authn
{
  "access_token": {
    "aud": "http://demo",
    "exp": 1616601217,
    "jti": "bb8ed933-0d2f-4c7c-b00c-75b978f0222e",
    "sub": "alice"
  },
  "exp": 1616601217,
  "refresh_token": {
    "aud": "http://demo",
    "exp": 1735689600,
    "jti": "de88cb24-e88f-4f1b-81e8-30d6d34cb897",
    "sub": "alice"
  }
}
```

This behavior persists even after launching the JWK service. When JOSE is able to reach the JWK url at startup, the `access_token` and `refresh_token` keys are signed as expected.

For the moment, I can use scripting/probes in our kubernetes deployments to mitigate this risk by waiting for JWKs availability prior to starting Kraken, and restarting it in the event of an ERROR log message, but it'd be nice if it were more resilient, e.g. with a backoff retry, to account for out-of-order service startups in kube deployments.

Alternatively, if we had the ability to specify a `file` URL, then I could use secret injection and ensure the resource was available at container start.

Minimally, I think that JOSE should refuse to serve the content--or be configured to refuse to serve the content--if it cannot apply the signing.

**Comment by kpacha** [comment]
As you pointed out, the JWK is requested at booting. We built it that way because that's the only time the gateway build the pipes for every endpoint. If there is a problem with the signer middleware initialization, the gateway throws an error to the log and keeps the pipe without that middleware. Since the configuration is static and the keys are referred by their jti, the signing key is requested once and then it's kept in memory, because there can not be changes.

On the other hand, there are some issues requesting other ways to load the JWK. It's in the backlog but it has a very low priority (high cost, low value).

Finally, I agree with you regarding the error log not being clear enough. I'm pushing a PR adding a better error message.

**Comment by mattkendall** [comment]
Thank you for responding. I guess we'll just use scripting to ensure that the KrakenD container self destructs/restarts when this error message appears in the log.

**Comment by zoubarevm** [comment]
@kpacha I was wondering if an error should be thrown if the `validator` fails to find or load the JWK URL. I've had instances where no JWT validation takes place if the JWK endpoint is down.
