### ISSUE TITLE
Configurable option to use CertificateThumbprintSHA1 instead of KeyID for JWK cache construction

### ISSUE THREAD

**Issue by spencerhuang** [devopsfaith/krakend-jose#43]
Is your feature request related to a problem? Please describe.
An OAuth 2 authentication server has decided to implement the issuing of access token (JWT) and the issuing of JWK by using the same value in the kid field for both structures.

`
jwt
{
"wbaxrV5e7SwP979FZhipGL4grrzz6Huprgh8GhmYLXw",
"x5t": "h_qy14b0XfJGElJAqW2jjoEpzUc",
"kid": "KEY",
"alg": "RS256"...
}

jwk
{
"kty": "RSA",
"x5t#S256": "bD2Ba4uIs0lLNyZAg_4Fbs2PgjqsF3p9AA21_Xkye34",
"e": "AQAB",
"x5t": "-1VGrqVBZ-Cc2k21fMx5n9qv-xI",
"kid": "KEY",
"x5c": ...
`

My understanding of Krakend is as the following:
the jwk spec library (structure) https://godoc.org/gopkg.in/square/go-jose.v2#JSONWebKey
auth0 creating jwk cache https://github.com/auth0-community/auth0-go/blob/master/key_cacher.go#L67
krakend-jose utilizing jwk cache https://github.com/devopsfaith/krakend-jose/blob/master/jwk.go#L43

To resolve this issue, I would have to fork the auth0-go library, modify the jwk cache construction, change how Krakend-jose uses that package, and then maintain my own implementation.

Describe the solution you'd like
It appears that krakend-jose is only using the ADD and the GET of aut0-go library, be great if it provides an option to use x5t as the key of jwk cache and we can set it as part of extra_config.

Describe alternatives you've considered
Change how that specific auth server provides token, but that's proprietary, not open source.

Additional context

**Comment by kpacha** [comment]
Can you please elaborate on what's the problem with going with `kid` if it's present in both parts (the key at the JWK and token itself)?

**Comment by spencerhuang** [comment]
> Can you please elaborate on what's the problem with going with `kid` if it's present in both parts (the key at the JWK and token itself)?

Thank you @kpacha for the quick response.

My use case is  when I am dealing with multi-tenants and each tenant has its own proprietary authentication server instance; yet, I want to use krakend in this multi-tenant manner. 

Then, I would have jwk-url to receive a list of jwk like so:
```
  "keys": [
        {
            "kty": "RSA",
            "x5t#S256": "bD2Ba4uIs0lLNyZAg_4Fbs2PgjqsF3p9AA21_Xkye34",
            "e": "AQAB",
            "x5t": "-1VGrqVBZ-Cc2k21fMx5n9qv-xI",
            "kid": "KEY",
            "x5c": [
                ""
            ],
            "key_ops": [
                "encrypt",
                "verify",
                "wrapKey"
            ],
            "alg": "RS256",
            "n": ""
        },
        {
            "kty": "RSA",
            "x5t#S256": "wbaxrV5e7SwP979FZhipGL4grrzz6Huprgh8GhmYLXw",
            "e": "AQAB",
            "x5t": "h_qy14b0XfJGElJAqW2jjoEpzUc",
            "kid": "KEY",
            "x5c": [
                ""
            ],
            "key_ops": [
                "encrypt",
                "wrapKey",
                "verify"
            ],
            "alg": "RS256",
            "n": ""
        }
    ]
```
As a result, AuthServer 1 would have jwk1 and AuthServer 2 would have jwk2, all of them would have kid's value as KEY. The problem is that when krakend receives a request with jwt, it has to go to jwk cache to locate the correct key entry in order to validate. With the current krakend-jose implementation, the second jwk2 would collide and replace jwk1 because their kid are the same, then requests with jwt generated from AuthServer 1 would fail.

**Comment by gnurik** [comment]
using kid + x5t is a collision resistant approach when dealing with multiple IdPs. Found a deeper analysis on this in https://redthunder.blog/2017/06/08/jwts-jwks-kids-x5ts-oh-my/

**Comment by arnavarro** [comment]
Currently, when krakend-jose is used to validate JWT tokens, the plugin uses the JWT's kid field in order to identify the JWK certificate that needs to be used to validate the JWT token. Since the kid field is an arbitrary field that is set to whatever the JWK certificate owner decides to, there's the possibility of collision in that 2 or more JWK certificate that have been stored by krakend-jose can have the same kid field – this means that krakend-jose would not know which JWK to use to validate the JWT token.

To address this issue, we feel that a better identifier would be the x5t field which is the x509's certificate's thumbprint. In the cases where multiple JWK certificates are stored – each would have a unique x5t field value making x5t a better JWK identifier field and decreases the chances of any collisions.

This feature request is to allow a user of krakend-jose to specify which field to use as key identifier in the configuration to let the user decide whether they should use kid by default, or x5t.

**Comment by kpacha** [comment]
ok, it looks like this feature request is getting some traction. So I think we should push it through the pipeline and start discussing the semantics and possible implementations.

From the top of my head, it will require a custom implementation of the `auth0.SecretProvider` interface by extending the `auth0.JWKClient` type, so this method (https://github.com/auth0-community/auth0-go/blob/master/jwk_client.go#L117-L125) can be decorated or replaced depending on the strategy required by the configuration. It will also affect the `NewFileKeyCacher` function, since ther will be more than a single way to identify the key used for a given token.

Should we implement 2 more strategies on top of the actual one (one for using just x5t and other for a combination of kid and x5f) and add a new `key_identify_strategy` config param?

**Comment by pelegn** [comment]
Hey @kpacha,
I've been working on this feature with Andres. we forked krakend-jose & auth0 in order to be able to support this change.
We have a working fork of this feature in the 2 repositories.
The places you pointed out are really the places we've added the changes.

Should I open a PR for both repos?

**Comment by kpacha** [comment]
why do we need to change the auth0 repo? Can't we add the implementation of the `auth0.SecretProvider` here?

Please. @pelegn , go ahead and open a PR here so we can start checking implementation ideas
